# upcheck Makefile — the fleet four-verb contract.
# Generated by `conform init`; conform checks it on every `make check`.

.DEFAULT_GOAL := check

SHELL := /bin/bash
.SHELLFLAGS := -euo pipefail -c

.PHONY: check audit help vet lint test build selfcheck race vuln

help: ## Show this help — the 3 verbs, identical in every dkoosis repo
	@awk 'BEGIN {FS = ":.*##"} /^[a-zA-Z0-9_.-]+:.*?## / { printf "  \033[36m%-14s\033[0m %s\n", $$1, $$2 }' $(MAKEFILE_LIST)

check: vet lint test build selfcheck ## Fast gate — vet + lint + test + build + conform. Pre-commit; required in CI.
	@echo "=== check pass ==="

audit: check race vuln ## Exhaustive validation — the gate, plus race and vulnerabilities
	@echo "=== audit pass ==="

vet: ## Run go vet
	go vet ./...

lint: ## Run golangci-lint (version pinned in .sandbox/project.conf)
	golangci-lint run ./...

test: ## Run tests with coverage
	go test -cover ./...

build: ## Compile everything
	go build ./...

# conform is pinned as a go.mod tool dependency (go.sum-verified); bumping the
# pin is a deliberate PR. It is a tool, not a runtime import — the zero-
# dependency rule in .claude/rules/standard-repo.md is about go list -deps.
selfcheck: ## Run conform (fleet SDLC checker) against this repo
	go tool conform

race: ## Run tests with the race detector (fresh run)
	go test -race -count=1 -cover ./...

vuln: ## Scan for known vulnerabilities
	govulncheck ./...
