#!/usr/bin/env bash
# go-sandbox lib-activate.sh — local dev environment activation
# Sourced by generated activate.sh. Requires: _SANDBOX_DIR set by caller.

# shellcheck source=/dev/null
source "$_SANDBOX_DIR/project.conf"

# Detect platform
_CODEX_OS=$(uname -s | tr '[:upper:]' '[:lower:]')
_CODEX_ARCH=$(uname -m)
case "$_CODEX_ARCH" in
  x86_64) _CODEX_ARCH="amd64" ;;
  aarch64|arm64) _CODEX_ARCH="arm64" ;;
esac
_CODEX_PLATFORM="${_CODEX_OS}-${_CODEX_ARCH}"

_REPO_DIR="$(cd "$_SANDBOX_DIR/.." && pwd)"

# The Go environment lives in lib-env.sh, which setup sources too — one file,
# two consumers, so the caches setup warms are the caches this reads.
# shellcheck source=/dev/null
source "$_SANDBOX_DIR/lib/lib-env.sh"

# Repo-local customization seam. The shared lib stays byte-identical fleet-wide;
# anything repo-specific lives here and survives a re-pull from GO_SANDBOX_REF.
if [ -f "$_SANDBOX_DIR/local-activate.sh" ]; then
  . "$_SANDBOX_DIR/local-activate.sh"
fi

# Performance (GOMAXPROCS is set in lib-env.sh)
ulimit -n 4096 2>/dev/null || true

# Ubuntu fd-find workaround — shim lives in a gitignored cache dir, not root bin/
_SHIM_DIR="$_REPO_DIR/.sandbox/cache/shims"
if command -v fdfind >/dev/null 2>&1 && ! command -v fd >/dev/null 2>&1; then
  mkdir -p "$_SHIM_DIR" 2>/dev/null || true
  ln -sf "$(command -v fdfind)" "$_SHIM_DIR/fd" 2>/dev/null || true
fi

# PATH: prebuilt platform binaries + shims first, straight from .sandbox/
# (no root bin/ mirror — keeps `ls` at repo root legible). Non-existent
# entries are harmlessly ignored by the shell's PATH lookup.
_PREBUILT_DIR="$_SANDBOX_DIR/bin/$_CODEX_PLATFORM"
export PATH="$_SHIM_DIR:$_PREBUILT_DIR:$PATH"

# Helper: available commands
sandbox-help() {
  echo "Build & QA:"
  if [ "$BUILD_SYSTEM" = "mage" ]; then
    echo "  mage              # Default QA target"
    echo "  mage qa           # Full quality gate"
  else
    echo "  make scan          # Fast inner loop: vet+lint+test on changed packages"
    echo "  make check         # Full repo: vet + lint + test + build"
    echo "  make audit         # Exhaustive: check + race + eval + dupl + vuln (may timeout in sandbox)"
    echo "  make doctor        # Validate toolchain"
  fi
  echo ""
  echo "Formatting:"
  echo "  gofumpt -w <file>    # Format Go file (strict)"
  echo "  goimports -w <file>  # Fix imports"
  echo ""
  echo "Code Navigation:"
  echo "  snipe def <symbol>   # Jump to definition"
  echo "  snipe callers <sym>  # Find callers"
  echo "  snipe search \"text\"  # Text search"
}

# Report tool status — derived from project.conf, not hardcoded
# zsh doesn't word-split unquoted scalars; use ${=VAR} for SH_WORD_SPLIT.
if [ -n "${ZSH_VERSION:-}" ]; then
  _REQUIRED_TOOLS=(${=BASE_IMAGE_TOOLS} ${=PREBUILT_TOOLS})
else
  # shellcheck disable=SC2206
  _REQUIRED_TOOLS=($BASE_IMAGE_TOOLS $PREBUILT_TOOLS)
fi
_TOOLS_OK=0
_TOOLS_MISS=0
_TOOLS_TOTAL=${#_REQUIRED_TOOLS[@]}
for _t in "${_REQUIRED_TOOLS[@]}"; do
  if command -v "$_t" >/dev/null 2>&1; then
    _TOOLS_OK=$((_TOOLS_OK + 1))
  else
    _TOOLS_MISS=$((_TOOLS_MISS + 1))
  fi
done

echo "$PROJECT_NAME environment activated (${_CODEX_PLATFORM})"
echo "  Tools: ${_TOOLS_OK}/${_TOOLS_TOTAL} required"
if [ "$_TOOLS_MISS" -gt 0 ]; then
  echo "  WARNING: ${_TOOLS_MISS} tool(s) missing — run 'make doctor' for details"
fi

# Surface last setup/maintenance health report (always, even when healthy)
_REPORT_FILE="$_REPO_DIR/.sandbox/setup-report.json"
if [ -f "$_REPORT_FILE" ] && command -v jq >/dev/null 2>&1; then
  _HEALTH=$(jq -r '"\(.status) (phase=\(.phase), ts=\(.timestamp))"' "$_REPORT_FILE" 2>/dev/null)
  if [ -n "$_HEALTH" ] && [ "$_HEALTH" != "null" ]; then
    echo "  Health: $_HEALTH"
    _FATAL_COUNT=$(jq -r '.fatals | length' "$_REPORT_FILE" 2>/dev/null)
    _WARN_COUNT=$(jq -r '.warnings | length' "$_REPORT_FILE" 2>/dev/null)
    if [ "${_FATAL_COUNT:-0}" -gt 0 ] || [ "${_WARN_COUNT:-0}" -gt 0 ]; then
      echo "    fatals=${_FATAL_COUNT:-0} warnings=${_WARN_COUNT:-0} — see $_REPORT_FILE"
    fi
  fi
else
  echo "  Health: no report (generated by sandbox setup/maintenance)"
fi
unset _REPORT_FILE _HEALTH _FATAL_COUNT _WARN_COUNT

echo "  Run 'sandbox-help' for available commands"

unset _CODEX_OS _CODEX_ARCH _CODEX_PLATFORM _PREBUILT_DIR _SHIM_DIR _TOOLS_OK _TOOLS_MISS _TOOLS_TOTAL _REQUIRED_TOOLS _REPO_DIR _t
